### Get all user
GET http://localhost:2000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imx1aXMuYXJkaWxhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoic2Fsa2Zqc2RsYWtqZmxkYXM7amZkbHNhZml1aGV3aXJmaCIsImlhdCI6MTY2MjUwOTc2OCwiZXhwIjoxNjYyNTEwMzY4fQ._frbtMMA6hHmHfaxq6boAZNCgw8wEPKSxzZ-E2cgzfY

### Get one user
GET http://localhost:2000/api/user/x5kUjzl8T4TtQ1oE84vOB
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLnBhcnJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2O2FiYzsiLCJpYXQiOjE2NjI1MTM2ODYsImV4cCI6MTY2MjUxNDI4Nn0.EKCJVqBqniIR5XPX11lFJdDV5S2G1_yco4PHDcaK0tM

### Save a new user
POST http://localhost:2000/api/user/signup
Content-Type: application/json

{
  "name": "Luis",
  "lastName": "Ardila",
  "email": "luis.ardila@gmail.com",
  "password": "salkfjsdlakjfldas;jfdlsafiuhewirfh"
}

### Delete a user by id
DELETE http://localhost:2000/api/user/2XYz-GSfWSzER25w4Fr8l

### Update a user by id
PATCH http://localhost:2000/api/user/y_omIXwPabKD8nwrmD0X_
Content-Type: application/json

{
  "email": "caleb.parra@gmail.com"
}

### Save a url
POST http://localhost:2000/api/url/
Content-Type: application/json

{
  "link": "https://www.linkedin.com/feed/update/urn:li:share:6965311557555646464?utm_source=linkedin_share&utm_medium=member_desktop_share&utm_content=post"
}

### Get url
GET http://localhost:2000/api/url/ns1gn_

### 404 error
GET http://localhost:2000/route/that/does/not/exists

### Login
POST http://localhost:2000/api/user/login
Content-Type: application/json

{
  "email": "luis.ardila@gmail.com",
  "password": "salkfjsdlakjfldas;jfdlsafiuhewirfh"
}

### Login
POST http://localhost:2000/api/user/login
Content-Type: application/json

{
  "email": "caleb.parra@gmail.com",
  "password": "123456;abc;"
}

### Create role
POST http://localhost:2000/api/role
Content-Type: application/json

{
  "id": "2",
  "name": "user"
}

### Get a role
GET http://localhost:2000/api/role/2
Content-Type: application/json

### Refresh user token
GET http://localhost:2000/api/user/refreshAccessToken/x5kUjzl8T4TtQ1oE84vOB
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhbGViLnBhcnJhQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiMTIzNDU2O2FiYzsiLCJpYXQiOjE2NjI1MTM2ODYsImV4cCI6MTY2MjUxNzI4Nn0.gpfhczqHiN94Sis8s1icT-lVJJn2b_1cGjOH72ei1R4
