GET http://localhost:2000/

###
POST http://localhost:2000/

###
GET http://localhost:2000/user

###
POST http://localhost:2000/user
Content-Type: application/json

{
  "name": "Caleb",
  "email": "caleb.parra@gmail.com"
}

###
DELETE http://localhost:2000/user/WOqvbXh27H4cNDKdiYnis

###
PATCH http://localhost:2000/user/csg-FFPXgvrcy3GKbvntC
Content-Type: application/json

{
  "email": "c.parra@gmail.com"
}

###
GET http://localhost:2000/api/docs
